"""Initial ScopeMaker schema

Revision ID: 05ef28ecd692
Revises: 
Create Date: 2026-08-06 22:47:20.241270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # referenced by the rendered JSONB(astext_type=...)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05ef28ecd692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('sso_provider', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_sso_subject'), ['sso_subject'], unique=False)

    op.create_table('api_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_token_prefix'), ['token_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('clauses',
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('division_code', sa.String(length=2), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('system_key', sa.String(length=120), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clauses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_division_code'), ['division_code'], unique=False)
        batch_op.create_index('ix_clauses_lookup', ['organization_id', 'division_code', 'category', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_clauses_system', ['division_code', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_system_key'), ['system_key'], unique=True)

    op.create_table('invitations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('memberships',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('procore_connections',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('grant_type', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.String(length=60), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('procore_user_id', sa.String(length=60), nullable=True),
    sa.Column('procore_user_name', sa.String(length=255), nullable=True),
    sa.Column('procore_user_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('connected_by_id', sa.String(length=36), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procore_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procore_connections_organization_id'), ['organization_id'], unique=True)

    op.create_table('projects',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('architect_name', sa.String(length=255), nullable=True),
    sa.Column('engineer_name', sa.String(length=255), nullable=True),
    sa.Column('contractor_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_method', sa.String(length=60), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('procore_project_id', sa.String(length=60), nullable=True),
    sa.Column('procore_company_id', sa.String(length=60), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_projects_procore', ['organization_id', 'procore_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_procore_project_id'), ['procore_project_id'], unique=False)

    op.create_table('scope_templates',
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('division_code', sa.String(length=2), nullable=True),
    sa.Column('trade_name', sa.String(length=160), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('system_key', sa.String(length=120), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_templates_division_code'), ['division_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_templates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_templates_system_key'), ['system_key'], unique=True)
        batch_op.create_index('ix_templates_org_division', ['organization_id', 'division_code'], unique=False)

    op.create_table('spec_sections',
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('division_code', sa.String(length=2), nullable=False),
    sa.Column('related_divisions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_universal', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('system_key', sa.String(length=120), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spec_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spec_sections_division_code'), ['division_code'], unique=False)
        batch_op.create_index('ix_spec_sections_lookup', ['organization_id', 'division_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_spec_sections_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spec_sections_system_key'), ['system_key'], unique=True)

    op.create_table('bid_packages',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('division_code', sa.String(length=2), nullable=True),
    sa.Column('trade_name', sa.String(length=160), nullable=True),
    sa.Column('subcontractor_name', sa.String(length=255), nullable=True),
    sa.Column('base_bid_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bid_due_date', sa.Date(), nullable=True),
    sa.Column('procore_bid_package_id', sa.String(length=60), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bid_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bid_packages_division_code'), ['division_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_packages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_packages_procore_bid_package_id'), ['procore_bid_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_packages_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_bid_packages_project_number', ['project_id', 'number'], unique=False)

    op.create_table('clause_suppressions',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('clause_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'clause_id', name='uq_suppression_org_clause')
    )
    with op.batch_alter_table('clause_suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clause_suppressions_clause_id'), ['clause_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clause_suppressions_organization_id'), ['organization_id'], unique=False)

    op.create_table('scopes',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('bid_package_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exhibit_label', sa.String(length=60), nullable=False),
    sa.Column('division_code', sa.String(length=2), nullable=True),
    sa.Column('trade_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('numbering_style', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('base_bid_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('alternates_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('adjustments_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('procore_commitment_id', sa.String(length=60), nullable=True),
    sa.Column('procore_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bid_package_id'], ['bid_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scopes_bid_package_id'), ['bid_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scopes_division_code'), ['division_code'], unique=False)
        batch_op.create_index('ix_scopes_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scopes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scopes_procore_commitment_id'), ['procore_commitment_id'], unique=False)
        batch_op.create_index('ix_scopes_project', ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scopes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scopes_status'), ['status'], unique=False)

    op.create_table('scope_revisions',
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'version', name='uq_revision_scope_version')
    )
    with op.batch_alter_table('scope_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_revisions_scope_id'), ['scope_id'], unique=False)

    op.create_table('scope_sections',
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_numbered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'key', name='uq_section_scope_key')
    )
    with op.batch_alter_table('scope_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_sections_scope_id'), ['scope_id'], unique=False)

    op.create_table('scope_items',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('text_html', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_clause_id', sa.String(length=36), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['scope_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['scope_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_items_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_items_section_id'), ['section_id'], unique=False)
        batch_op.create_index('ix_scope_items_section_pos', ['section_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_items', schema=None) as batch_op:
        batch_op.drop_index('ix_scope_items_section_pos')
        batch_op.drop_index(batch_op.f('ix_scope_items_section_id'))
        batch_op.drop_index(batch_op.f('ix_scope_items_parent_id'))

    op.drop_table('scope_items')
    with op.batch_alter_table('scope_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_sections_scope_id'))

    op.drop_table('scope_sections')
    with op.batch_alter_table('scope_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_revisions_scope_id'))

    op.drop_table('scope_revisions')
    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scopes_status'))
        batch_op.drop_index(batch_op.f('ix_scopes_project_id'))
        batch_op.drop_index('ix_scopes_project')
        batch_op.drop_index(batch_op.f('ix_scopes_procore_commitment_id'))
        batch_op.drop_index(batch_op.f('ix_scopes_organization_id'))
        batch_op.drop_index('ix_scopes_org_status')
        batch_op.drop_index(batch_op.f('ix_scopes_division_code'))
        batch_op.drop_index(batch_op.f('ix_scopes_bid_package_id'))

    op.drop_table('scopes')
    with op.batch_alter_table('clause_suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clause_suppressions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_clause_suppressions_clause_id'))

    op.drop_table('clause_suppressions')
    with op.batch_alter_table('bid_packages', schema=None) as batch_op:
        batch_op.drop_index('ix_bid_packages_project_number')
        batch_op.drop_index(batch_op.f('ix_bid_packages_project_id'))
        batch_op.drop_index(batch_op.f('ix_bid_packages_procore_bid_package_id'))
        batch_op.drop_index(batch_op.f('ix_bid_packages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_bid_packages_division_code'))

    op.drop_table('bid_packages')
    with op.batch_alter_table('spec_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_sections_system_key'))
        batch_op.drop_index(batch_op.f('ix_spec_sections_organization_id'))
        batch_op.drop_index('ix_spec_sections_lookup')
        batch_op.drop_index(batch_op.f('ix_spec_sections_division_code'))

    op.drop_table('spec_sections')
    with op.batch_alter_table('scope_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_templates_org_division')
        batch_op.drop_index(batch_op.f('ix_scope_templates_system_key'))
        batch_op.drop_index(batch_op.f('ix_scope_templates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scope_templates_division_code'))

    op.drop_table('scope_templates')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_procore_project_id'))
        batch_op.drop_index('ix_projects_procore')
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))
        batch_op.drop_index('ix_projects_org_name')

    op.drop_table('projects')
    with op.batch_alter_table('procore_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procore_connections_organization_id'))

    op.drop_table('procore_connections')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clauses_system_key'))
        batch_op.drop_index('ix_clauses_system')
        batch_op.drop_index(batch_op.f('ix_clauses_organization_id'))
        batch_op.drop_index('ix_clauses_lookup')
        batch_op.drop_index(batch_op.f('ix_clauses_division_code'))
        batch_op.drop_index(batch_op.f('ix_clauses_category'))

    op.drop_table('clauses')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_organization_id'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_sso_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
