"""Password reset tokens, account lockout, session epoch

Revision ID: 94e0f08f468b
Revises: 05ef28ecd692
Create Date: 2026-08-07 08:03:54.337956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e0f08f468b'
down_revision = '05ef28ecd692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_prefix'), ['token_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default is required, not optional: adding a NOT NULL column to
        # a table that already has rows fails without one. It is dropped again
        # below so the schema matches the model, where the default is applied
        # in Python.
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
        # Existing sessions carry no epoch and are rejected by the user loader,
        # so everyone is signed out once on upgrade. That is the correct
        # behaviour for a release that introduces session revocation.
        batch_op.add_column(sa.Column('session_epoch', sa.Integer(),
                                      nullable=False, server_default='1'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('failed_login_count', server_default=None)
        batch_op.alter_column('session_epoch', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_epoch')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_prefix'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
