"""Render queue and scope row version

Revision ID: a0e2627d3a55
Revises: f2f61e899efa
Create Date: 2026-08-07 10:37:24.062133

"""
from alembic import op
import sqlalchemy as sa
# Alembic renders JSONB columns as JSONB(astext_type=Text()) without importing
# Text, which is a NameError the moment the migration runs. Importing it here
# means every generated migration has it whether or not it is used.
from sqlalchemy import Text  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'a0e2627d3a55'
down_revision = 'f2f61e899efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_jobs',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('fingerprint', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('result', sa.LargeBinary(), nullable=True),
    sa.Column('result_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_jobs_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_jobs_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index('ix_render_lookup', ['scope_id', 'format', 'fingerprint', 'status'], unique=False)
        batch_op.create_index('ix_render_queue', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('scopes', schema=None) as batch_op:
        # NOT NULL on a populated table needs a server default, dropped again
        # below so the schema matches the model.
        batch_op.add_column(sa.Column('row_version', sa.Integer(),
                                      nullable=False, server_default='1'))

    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.alter_column('row_version', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scopes', schema=None) as batch_op:
        batch_op.drop_column('row_version')

    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_render_queue')
        batch_op.drop_index('ix_render_lookup')
        batch_op.drop_index(batch_op.f('ix_render_jobs_scope_id'))
        batch_op.drop_index(batch_op.f('ix_render_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_render_jobs_expires_at'))

    op.drop_table('render_jobs')
    # ### end Alembic commands ###
