"""Two factor authentication

Revision ID: f2f61e899efa
Revises: 133d89ad9901
Create Date: 2026-08-07 08:40:11.199019

"""
from alembic import op
import sqlalchemy as sa
# Alembic renders JSONB columns as JSONB(astext_type=Text()) without importing
# Text, which is a NameError the moment the migration runs. Importing it here
# means every generated migration has it whether or not it is used.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2f61e899efa'
down_revision = '133d89ad9901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.Text(), nullable=True))
        # NOT NULL on a populated table needs a server default; both are
        # dropped again below so the schema matches the model.
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('mfa_confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('mfa_recovery_hashes',
                                      sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
                                      nullable=False, server_default='[]'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mfa_enabled', server_default=None)
        batch_op.alter_column('mfa_recovery_hashes', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_recovery_hashes')
        batch_op.drop_column('mfa_confirmed_at')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###
