"""Export the clause library for the static GitHub Pages demo.

GitHub Pages cannot run Flask, so the demo assembles exhibits in the browser.
The *data* it uses is exported from the real seed library by this script and
regenerated in CI, so the demo can never drift from what the application would
actually produce -- only the rendering is reimplemented, and that is a few
dozen lines.

Also writes a handful of real exhibits as standalone HTML, straight out of the
application's own renderer. Those are not a reimplementation of anything: they
are exactly what the app emits.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scopemaker import create_app  # noqa: E402
from scopemaker.data import (  # noqa: E402
    load_boilerplate,
    load_seed_clauses,
    load_seed_spec_sections,
)
from scopemaker.data.masterformat import DIVISIONS, normalize_code  # noqa: E402
from scopemaker.extensions import db  # noqa: E402
from scopemaker.models import BidPackage, Project  # noqa: E402
from scopemaker.models.library import CLAUSE_CATEGORIES  # noqa: E402
from scopemaker.services import library as library_service  # noqa: E402
from scopemaker.services.accounts import create_organization  # noqa: E402
from scopemaker.services.renderers import render_html  # noqa: E402
from scopemaker.services.scope_builder import ScopeDraft, build_scope  # noqa: E402
from scopemaker.services.seeding import seed_library  # noqa: E402

OUT = ROOT / "docs" / "demo"
SAMPLE_DIVISIONS = ["21", "22", "23", "26", "09", "31"]


def export_library() -> dict:
    """The seed library, in the shape the browser demo wants."""
    clauses = []
    for entry in load_seed_clauses():
        division = entry.get("division")
        clauses.append(
            {
                "key": entry["key"],
                "division": normalize_code(division) if division else None,
                "category": entry.get("category", "inclusion"),
                "default": bool(entry.get("default", False)),
                "position": int(entry.get("position", 0)),
                "text": " ".join(str(entry.get("text", "")).split()),
            }
        )

    sections = []
    for entry in load_seed_spec_sections():
        sections.append(
            {
                "key": entry["key"],
                "code": str(entry.get("code", "")),
                "title": str(entry.get("title", "")),
                "division": normalize_code(entry.get("division")),
                "related": [
                    code
                    for code in (normalize_code(c) for c in entry.get("related") or [])
                    if code
                ],
                "universal": bool(entry.get("universal", False)),
                "default": bool(entry.get("default", False)),
                "position": int(entry.get("position", 0)),
            }
        )

    return {
        "note": "Generated by scripts/build_demo.py from the real seed library. "
        "Do not edit by hand.",
        "divisions": [
            {"code": d.code, "title": d.title, "trades": list(d.trades)}
            for d in DIVISIONS
        ],
        "categories": CLAUSE_CATEGORIES,
        "boilerplate": load_boilerplate(),
        "clauses": clauses,
        "spec_sections": sections,
    }


def export_sample_exhibits() -> list[dict]:
    """Real exhibits, rendered by the application itself."""
    app = create_app("testing")
    manifest = []

    with app.app_context():
        db.create_all()
        seed_library()

        org = create_organization("Meridian Construction")
        org.legal_name = "Meridian Construction Group, LLC"
        org.address = "220 Grandview Ave, Suite 400, Columbus, OH 43215"
        db.session.flush()

        project = Project(
            organization_id=org.id,
            name="Riverside Medical Center",
            number="2024-118",
            address="1400 River Road",
            city="Columbus",
            state="OH",
            owner_name="Riverside Health System",
            architect_name="Whitfield Architects",
            contractor_name="Meridian Construction Group, LLC",
            delivery_method="CMAR",
        )
        db.session.add(project)
        db.session.commit()

        for index, code in enumerate(SAMPLE_DIVISIONS, start=1):
            trade = next(d.default_trade for d in DIVISIONS if d.code == code)
            package = BidPackage(
                project_id=project.id, organization_id=org.id,
                number=f"BP-{code}A", name=trade, division_code=code, trade_name=trade,
            )
            db.session.add(package)
            db.session.commit()

            scope = build_scope(
                ScopeDraft(
                    organization_id=org.id,
                    division_code=code,
                    project_id=project.id,
                    bid_package_id=package.id,
                    clause_ids=library_service.default_clause_ids(org.id, code),
                    spec_section_ids=library_service.default_spec_section_ids(org.id, code),
                    base_bid_amount=250_000 * index + 175_400,
                )
            )
            html = render_html(scope, organization=org, standalone=True)
            filename = f"exhibit-{code}.html"
            (OUT / "exhibits" / filename).write_text(html, encoding="utf-8")
            manifest.append(
                {
                    "division": code,
                    "trade": trade,
                    "items": scope.item_count,
                    "file": f"exhibits/{filename}",
                }
            )
            print(f"  Division {code} {trade}: {scope.item_count} items -> {filename}")

    return manifest


def main() -> int:
    (OUT / "exhibits").mkdir(parents=True, exist_ok=True)

    library = export_library()
    (OUT / "library.json").write_text(
        json.dumps(library, separators=(",", ":"), ensure_ascii=False), encoding="utf-8"
    )
    size = (OUT / "library.json").stat().st_size
    print(
        f"library.json: {len(library['clauses'])} clauses, "
        f"{len(library['spec_sections'])} sections, {size // 1024} KB"
    )

    manifest = export_sample_exhibits()
    (OUT / "exhibits" / "manifest.json").write_text(
        json.dumps(manifest, indent=1), encoding="utf-8"
    )

    # The demo renders with the application's own document stylesheet, so the
    # preview matches the real output rather than approximating it.
    shutil.copyfile(
        ROOT / "scopemaker" / "static" / "css" / "document.css",
        OUT / "document.css",
    )
    print("copied document.css")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
