"""Markdown export.

Useful for archiving scopes in a repository and for reviewing what actually
changed between two revisions in a plain text diff -- the numbered labels are
written literally, so a moved clause shows up as a moved number.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any

from ...models import Scope
from ...models.scope import SectionKind
from ..sanitize import strip_html
from .html import DocumentLine, build_document


def _money(value: Decimal | None, currency: str) -> str:
    if value is None:
        return "TBD"
    symbol = "$" if currency in ("USD", "CAD", "AUD") else ""
    return f"{symbol}{Decimal(value):,.2f}"


def _render_lines(lines: list[DocumentLine], out: list[str]) -> None:
    for line in lines:
        indent = "    " * line.depth
        out.append(f"{indent}{line.label} {line.text}")
        _render_lines(line.children, out)


def render_markdown(scope: Scope, *, organization: Any = None) -> bytes:
    doc = build_document(scope, organization=organization)
    out: list[str] = [f"# {doc.title}", ""]

    subtitle = " – ".join(p for p in (doc.division_label, doc.trade_name) if p)
    if subtitle:
        out += [f"**{subtitle}**", ""]

    facts = [
        ("Project", " ".join(p for p in (doc.project.get("number"),
                                         doc.project.get("name")) if p)),
        ("Location", doc.project.get("location")),
        ("Bid Package", " ".join(p for p in (doc.bid_package.get("number"),
                                             doc.bid_package.get("name")) if p)),
        ("Subcontractor", doc.bid_package.get("subcontractor")),
        ("Status", f"{doc.status} (v{doc.version})"),
    ]
    facts = [(label, value) for label, value in facts if value]
    if facts:
        out += ["| | |", "|---|---|"]
        out += [f"| **{label}** | {value} |" for label, value in facts]
        out.append("")

    for section in doc.enabled_sections:
        out += [f"## {section.number} {section.heading}", ""]

        body = strip_html(section.body_html)
        if body:
            out += [body, ""]

        if section.kind == SectionKind.RECAP:
            out += ["| Item | Amount |", "|---|---:|"]
            for row in doc.recap_rows:
                label = f"**{row.label}**" if row.is_total else row.label
                amount = _money(row.amount, doc.currency)
                out.append(f"| {label} | {amount} |")
            out.append("")
        elif section.lines:
            rendered: list[str] = []
            _render_lines(section.lines, rendered)
            out += rendered
            out.append("")

    out += ["---", f"*Generated by ScopeMaker on {doc.generated_at}.*", ""]
    return "\n".join(out).encode("utf-8")
